### ISSUE TITLE
Quest Diamond Shield [#660] invalid items

### ISSUE THREAD

**Issue by alphaest** [GTNewHorizons/NewHorizons#1345]
Currently:
TGregworks:tGregToolPartLargePlate:97 x2 [material:8=Diamond]
TGregworks:tGregToolPartToughBind:97 x1 [material:8=Diamond]
TGregworks:tGregToolPartToughRod:97 x2 [material:8=Diamond]

But the item damage is actually :95 for all of them.

Could be a duplicate of #1194

**Comment by Dream-Master** [comment]
Ok will look at it. I thought this was fixed ?

**Comment by alphaest** [comment]
I checked this with the current build in SP after /load and /refresh so i guess it was not fixed.

**Comment by Dream-Master** [comment]
ok will check.

**Comment by Drobac** [comment]
None of the parts made by Tinkers Gregworks seem to be detectable in quests

**Comment by Dream-Master** [comment]
```
{
      "questID": 660,
      "name": "Diamond Shield",
      "description": "Your iron shield got very old. With a shield made from diamond plates you can maintain block up to 5 seconds.",
      "isMain": false,
      "isSilent": false,
      "lockedProgress": false,
      "simultaneous": false,
      "globalParticipation": 0.0,
      "globalQuest": false,
      "globalShare": true,
      "autoClaim": false,
      "repeatTime": -1,
      "sounds": {
        "complete": "random.levelup",
        "update": "random.levelup"
      },
      "logic": "AND",
      "taskLogic": "AND",
      "icon": {
        "id": "battlegear2:shield.diamond",
        "Count": 1,
        "OreDict": "",
        "Damage": 0
      },
      "visibility": "UNLOCKED",
      "tasks": [
        {
          "partialMatch": true,
          "ignoreNBT": false,
          "consume": false,
          "autoConsume": false,
          "requiredItems": [
            {
              "id": "TGregworks:tGregToolPartLargePlate",
              "Count": 2,
              "OreDict": "",
              "Damage": 97,
              "tag": {
                "material:8": "Diamond"
              }
            },
            {
              "id": "TGregworks:tGregToolPartToughBind",
              "Count": 1,
              "OreDict": "",
              "Damage": 97,
              "tag": {
                "material:8": "Diamond"
              }
            },
            {
              "id": "TGregworks:tGregToolPartToughRod",
              "Count": 2,
              "OreDict": "",
              "Damage": 97,
              "tag": {
                "material:8": "Diamond"
              }
            }
          ],
          "taskID": "bq_standard:retrieval"
        },
        {
          "partialMatch": true,
          "ignoreNBT": true,
          "requiredItems": [
            {
              "id": "battlegear2:shield.diamond",
              "Count": 1,
              "OreDict": "",
              "Damage": 0
            }
          ],
          "taskID": "bq_standard:crafting"
        }
      ],
      "rewards": [
        {
          "choices": [
            {
              "id": "minecraft:spawn_egg",
              "Count": 1,
              "OreDict": "",
              "Damage": 57
            },
            {
              "id": "minecraft:spawn_egg",
              "Count": 1,
              "OreDict": "",
              "Damage": 62
            },
            {
              "id": "enhancedlootbags:lootbag",
              "Count": 1,
              "OreDict": "",
              "Damage": 5
            }
          ],
          "rewardID": "bq_standard:choice"
        },
        {
          "rewards": [
            {
              "id": "dreamcraft:item.CoinSmithI",
              "Count": 2,
              "OreDict": "",
              "Damage": 0
            },
            {
              "id": "dreamcraft:item.CoinSurvivorI",
              "Count": 2,
              "OreDict": "",
              "Damage": 0
            }
          ],
          "rewardID": "bq_standard:item"
        }
      ],
      "preRequisites": [
        89
      ]
    },
```

**Comment by Dream-Master** [comment]
Now all of them have meta id 97.

**Comment by alphaest** [comment]
It was :97 before in quest and needed to be changed to :95 since diamond parts in game are all with :95

**Comment by Dream-Master** [comment]
ah ok will change it.

**Comment by Dream-Master** [comment]
So with version 17 all will work fine.

**Comment by Dream-Master** [comment]
Need TGregworks version 17
