### ISSUE TITLE
Mold for rotor is used up in the Fluid Solidifier

### ISSUE THREAD

**Issue by masterqgj** [GTNewHorizons/NewHorizons#1985]
#### Which modpack version are you using?
GTNH (latest 2.0.0.0) (i believe it is 2.0.0.2 on twitch?)
#
#### If in multiplayer; On which server does this happen? 
MP (Server Epsilon)
#
#### What did you try to do, and what did you expect to happen?
I made a mold for a rotor for the fluid solidifier, supplied enough molten steel to it and expected to get several rotors out of it.
#
#### What happend instead? (Attach screenshots if needed)
I only got one rotor out of it, before the mold disappeared, the remaining steel was quite useless
#
#### What do you suggest instead/what changes do you propose?
Do not remove the mold after one cycle

**Comment by Dream-Master** [comment]
So far I know this was fixed @Mineanplay ?
But I will check

**Comment by Dream-Master** [comment]
Recipe seems to be valid and not comsume the Mold.
Will check it ingame:

`GT_Values.RA.addFluidSolidifierRecipe(ItemList.Shape_Mold_Rotor.get(0L, new Object[0]),  aMaterial.getMolten(612L), GT_OreDictUnificator.get(OrePrefixes.rotor, aMaterial, 1L), 100, 60);`

**Comment by masterqgj** [comment]
Well, at least last weekend, when i tried to make the rotor this way, the mold was gone. Since it was on the official server i think the issue still occurs. #1968 seems (!) to be a similar issue if i understand No. 2 correctly (i'm not 100% sure though)

**Comment by Dream-Master** [comment]
I will check it and it will be in the next update 2.0.0.1

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/30617769-dbd13a22-9d97-11e7-891d-64ae382bca88.png)
