### ISSUE TITLE
Elite Arc Furnaces only have one output slot

### ISSUE THREAD

**Issue by DualBallers** [GTNewHorizons/NewHorizons#3863]
2.0.6.0

Elite Arc Furnace I and II only have one output slot.
All other arc furnaces uses all four output slots correctly.

![image](https://user-images.githubusercontent.com/30087707/49076199-bdba6580-f238-11e8-96f9-b9b9adbd1a57.png)

![image](https://user-images.githubusercontent.com/30087707/49076218-c874fa80-f238-11e8-9e82-104315755854.png)

**Comment by Dream-Master** [comment]
will check

**Comment by DualBallers** [comment]
Ok, forgot to check the higher tiers, but this one is still missing in your latest commit :-)

`
11070, "basicmachine.arcfurnace.tier.06", "Elite Arc Furnace", 6, "",
				GT_Recipe.GT_Recipe_Map.sArcFurnaceRecipes, 1, 1, 128000, 0, 1, "ArcFurnace.png",
`

**Comment by Dream-Master** [comment]
will check

**Comment by Dream-Master** [comment]
fixed @DualBallers

**Comment by DualBallers** [comment]
Maybe I'm dense, but looking at the file I still see this for the Elite Arc Furnace

GT_Recipe.GT_Recipe_Map.sArcFurnaceRecipes, 1, **1**, 128000, 0, 1, "ArcFurnace.png",
