### ISSUE TITLE
Water Lilly Texture Still Borked 2.0.7.5

### ISSUE THREAD

**Issue by shawnbyday** [GTNewHorizons/NewHorizons#4866]
#### Which modpack version are you using?
2.0.7.5
#
#### If in multiplayer; On which server does this happen? 
Private Server
#
#### What do you suggest instead/what changes do you propose?
Reported in 2.0.7.4dev. Can't recall if it was fixed...in my install of 2.0.7.5 it is still missing.

**Comment by bartimaeusnek** [comment]
should be fixed indev IIRC

**Comment by shawnbyday** [comment]
> should be fixed indev IIRC

Ok sorry man. I thought it was in the 2075 release. Feel free to close this.

**Comment by ScriptedPiky** [comment]
Confirming this bug still persists in 2.0.7.5. Found on Zeta when breeding crops
![2019-07-22_12 52 12](https://user-images.githubusercontent.com/41557212/61817546-abaeb800-ae03-11e9-9a74-c673b8f9b1a0.png)

**Comment by bartimaeusnek** [comment]
@ScriptedPiky Zeta and the officials are currently running the same version

**Comment by ScriptedPiky** [comment]
> @ScriptedPiky Zeta and the officials are currently running the same version

Ohhhhhh I forgot Zeta wasn't on the Dev version, whoopies
