### ISSUE TITLE
Draconic armor flight speed modifier not working

### ISSUE THREAD

**Issue by Alexdoru** [GTNewHorizons/NewHorizons#5142]
#### Which modpack version are you using?
GTNH 2.0.8.0.b
#
#### What did you try to do, and what did you expect to happen?
Set the flight speed to the max and expected to fly like a shooting star and ended up disapointed as it did nothing.

#
#### What do you suggest instead/what changes do you propose?
Try to fix it as the armor is really expensive to make and the player has to complete A LOT of quests to unlock it. What's the point of having two tabs of endgame legendary quests to unlock an armor that is broken ?

**Comment by richardhendricks** [comment]
Our custom version is available at https://github.com/GTNewHorizons/Draconic-Evolution

**Comment by richardhendricks** [comment]
Looks like you have to hold down control to get the speed boost, I assume you are doing that?

https://github.com/GTNewHorizons/Draconic-Evolution/blob/master/src/main/java/com/brandon3055/draconicevolution/common/items/armor/DraconicArmor.java#L534

**Comment by Alexdoru** [comment]
First time I played GTNH I noticed that the sprinting mechanic is different from vanilla minecraft, one day some guy on discord said that it was GT++ that was modifying the sprinting mechanic. So I just test to launch the game without GT++ and now the armor is working properly and you can fly super fast.
I would recommend investigating how is GT++ modifying the sprinting mechanic ?

**Comment by richardhendricks** [comment]
Should be fixed with next dev release. Please retest.

**Comment by Alexdoru** [comment]
So I am testing the GTNH pre2.0.8.0 and with the costum GT++ version dream gave.
 The bug is still here, the sprint is still not behaving like vanilla minecraft and the draconic armor flight speed bug remains the same.
![image](https://user-images.githubusercontent.com/57050655/71380165-94504280-25ce-11ea-87e6-8b86694d13e2.png)

**Comment by Dream-Master** [comment]
@Alexdoru this bug not fixed. Not in any gt++ version i guess

**Comment by Josh5minus1** [comment]
It's fixed in the latest GT++ build.
