### ISSUE TITLE
Single Block Miners resetting work area

### ISSUE THREAD

**Issue by SeppDE** [GTNewHorizons/NewHorizons#5185]
#### Which modpack version are you using?

2.0.8.0b SSP

#### What did you try to do, and what did you expect to happen?

Relocated my Single Block GT Miner (HV one) to a new location that more ores get mined.

#### What happened instead? (Attach screenshots if needed)

After the first location got cleared you picking up the Miner, place it down in a new spot and the work area got resettet from 49x49 (HV one) to 1x1 without any user input.
It happens if you place it on a new spot or the same. The machine just loose the default work area of 49x49.

#### What do you suggest instead/what changes do you propose?

The Work Area of the Miner should stay on maximum or at least should "save" the last settings and not resetting. Perhaps that one is involved in the process? https://github.com/GTNewHorizons/GT5-Unofficial/commit/96db49fa7dd72899d2255a19b269e66e9acb8d19

**Comment by richardhendricks** [comment]
Must fix bug for 2.0.8.0 release

**Comment by Dream-Master** [comment]
@richardhendricks did you work on it ?

**Comment by richardhendricks** [comment]
Not yet, but this will be priority 1

**Comment by Dream-Master** [comment]
ok

**Comment by richardhendricks** [comment]
smdh, I didn't know we added radius config to the singleblocks as well. It's almost certainly something wrong here.

**Comment by richardhendricks** [comment]
Possible issue here
```java
https://github.com/GTNewHorizons/GT5-Unofficial/blob/experimental/src/main/java/gregtech/common/tileentities/machines/basic/GT_MetaTileEntity_Miner.java#L39
```
Cannot use a class variable to set a class variable. This should be initialized to -1, and then assigned during the constructor.

**Comment by richardhendricks** [comment]
Problem probably also exists with oil pumps
https://github.com/GTNewHorizons/GT5-Unofficial/blob/experimental/src/main/java/gregtech/common/tileentities/machines/basic/GT_MetaTileEntity_Pump.java#L58

May exist in multiblock ore miners and oil pumps, need to confirm order of initialization of class members.

**Comment by bartimaeusnek** [comment]
Addressed with 
https://github.com/GTNewHorizons/GT5-Unofficial/commit/c0265e9017d9b14e06a88f9eca54a88c786ae846

**Comment by richardhendricks** [comment]
No, it's not:

1.  You did not include the pumps
2. You did not fix the root problem = the mTier is being used before it is properly set in the constructor.  Move the assignment inside the constructors.
